// Tests the distribution generated by Java's Math.random() function.
public class TestRandom {
    public static void main(String[] args) {
        int N = Integer.parseInt(args[0]);
        int greaterThanHalf = 0;
        int lessOrEqualHalf = 0;

        for (int i = 0; i < N; i++) {
            double randomValue = Math.random();

            if (randomValue > 0.5) {
                greaterThanHalf++;
            } else {
                lessOrEqualHalf++;
            }
        }

        System.out.println("> 0.5: " + greaterThanHalf + " times");
        System.out.println("<= 0.5: " + lessOrEqualHalf + " times");

        if (lessOrEqualHalf == 0) {
            return;
        } else {
            double ratio = (double) greaterThanHalf / lessOrEqualHalf;
            System.out.println("Ratio (>0.5 / <=0.5): " + ratio);
        }
    }
}
